### ISSUE TITLE
NativeDemo iOS crashed with audio stream

### ISSUE THREAD

**Issue by cw35** [EricssonResearch/openwebrtc-examples#152]
always crashed while audio stream enabled. Crashed while audio_chain_get_samples is called...

**Comment by stefanalund** [comment]
Sounds strange. What device where you running and what client is on the B-side?

**Comment by RicardCampanya** [comment]
I have problems running the native app between iphone 4s and ipad air (issue: https://github.com/EricssonResearch/openwebrtc-examples/issues/151 ) but not between ipad air and iphone 5s, this issue suggested me to try  disabling audio in nativehandler and make a call. That works perfect and no crash. But it's strange, because I  made a videocall with audio (between air and 4s) one time without crashes. If you are using iphone 4s maybe the problem is the same that happens to me.

**Comment by stefanalund** [comment]
@RicardCampanya we are working hard on improving CPU usage for the full pipeline. At the moment it does not work very well (if at all) on older devices such as the iPhone 4s. The iPhone 5s is quite a lot faster and also has a 64-bit ARM chip.
