### ISSUE TITLE
Demo website does not work

### ISSUE THREAD

**Issue by sdroege** [EricssonResearch/openwebrtc-examples#172]
Chrome complains about
```
PermissionDeniedError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
```

Firefox complains about
```
NotFoundError: The object can not be found here.
```

when clicking on "join"

**Comment by sdroege** [comment]
When using 127.0.0.1 as hostname it fails on Chrome with
```
[object NavigatorUserMediaError]
```

**Comment by sdroege** [comment]
NativeCall demo on Android shows at least the self-view with the self hosted demo website.

**Comment by superdump** [comment]
I believe localhost is considered to be a secure origin, but we really need to sort out https support for the demo page.

Is there any more information from Firefox about the issue when clicking join? I know that there is an issue when using master of the channel server due to https://github.com/EricssonResearch/openwebrtc-examples/commit/8f7b847b5f2d0a267ef1eaea5f8b2f405af6a120.

**Comment by sdroege** [comment]
No more information, but I'll see if reverting that commit solves it.

**Comment by sdroege** [comment]
Now firefox complains about
```
InvalidCandidateError: Mismatch between mid and level - "video" is not the mid for level 0; "" is
```

but it works.

**Comment by sdroege** [comment]
Can this commit just be reverted then? Doesn't seem like a good idea to keep GIT master broken for months without a plan

**Comment by sdroege** [comment]
https://github.com/EricssonResearch/openwebrtc-examples/pull/181
