### ISSUE TITLE
Helper classes in Swift

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc-examples#25]
Implement the Helper classes in Swift as well.

**Comment by sentiasa** [comment]
Hi @jrosssavant, when I try to build your selfie-swift-attempt, I received:

/Users/Bertug/Downloads/openwebrtc-examples-selfie-swift-attempt/ios/OwrHelpers/OpenWebRTC-BridgingHeader.h:30:9: error: 'owr.h' file not found
#import "owr.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/Bertug/Downloads/openwebrtc-examples-selfie-swift-attempt/ios/OwrHelpers/OpenWebRTC-BridgingHeader.h'


Am I doing something wrong or missing out something? Or did you stop working on it?

**Comment by superdump** [comment]
@sentiasa This example uses the OpenWebRTC.framework installed from the iOS package. If you have not installed it, owr.h will not be found. How are you trying to build it?

**Comment by sentiasa** [comment]
Whatever I did, I couldn't figure out how to build it. I downloaded @jrosssavant 's SelfieSwift. Then, I created podfile in that directory and put:

platform :ios, '8.0'

target 'SelfieSwift' do
    pod 'OpenWebRTC', '~> 0.1'
    pod 'OpenWebRTC-SDK', :path => '../../../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end

However I got:
[!] No podspec found for `OpenWebRTC-SDK` in `../../../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`

Can you assist me on that, please?

**Comment by sentiasa** [comment]
@superdump Which ones do I need to install from here? https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

I'm going to use osX for building the project and test it on ios8

**Comment by superdump** [comment]
@sentiasa If you want to use the OpenWebRTC pod, try changing the include to `<owr/owr.h>`

**Comment by sentiasa** [comment]
@superdump When I followed `"https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC"` this documentation, I have done everything successfully until 'Using the Results - iOS Framework' but when I installed `openwebrtc-devel-0.1.0-ios-universal.pkg`, no folder and files are created in `' ~/Library/Developer/OpenWebRTC/ `' in my case. So I ended up dragging the framework from `Library/Frameworks/` and manually added into SelfieSwift demo. So I also stuck in adding the header because I don't have `~/Library/Developer/OpenWebRTC/iPhone.sdk/OpenWebRTC.framework/Headers`
either. 

Then I gave up in the previous step and I tried the pod. However whatever I've tried, `<owr/owr.h>` . Can I achieve what I am trying to achieve with podfile? Can you help me what I should write in the Podfile? But I want to highlight again that `~/Library/Developer/OpenWebRTC/iPhone.sdk/OpenWebRTC.framework/Headers` folder doesn't exist for me whatever I have done.

**Comment by jrosssavant** [comment]
@sentiasa:  As you guessed I have not worked on the SelfieSwift app in some time, but it was working at the time I last committed (8f2ccaf).  At that time the OpenWebRTC libraries were linked into the demo app under the assumption that the openwebrtc repository was fully built for iOS, and that the openwebrtc repository was adjacent to the openwebrtc-examples repository.  It looks like some changes have been made since that time to use the OpenWebRTC.framework - which I think is a great step forward.  But I can't tell you how to get the correct framework into ~/Library/Developer/OpenWebRTC/iPhone.sdk/; that framework is not present on my machine (nor even ~/Library/Developer/OpenWebRTC).  @superdump: is there a set of instructions that describes how to build and install the OpenWebRTC framework into that location?  I have an old cerbero-based build which installs into /Library/Frameworks/OpenWebRTC.framework, but not into ~/Library.

**Comment by superdump** [comment]
If you build the iOS package according to the build instructions and then install the the .pkg file as instructed, it will land there.

Another alternative is to move it to use cocoapods instead.

**Comment by superdump** [comment]
Oh, and the appropriate package file is available in the OpenWebRTC release.

**Comment by jrosssavant** [comment]
Thanks for pointing this out - I downloaded the .pkg from the release and now the SimpleDemoSwift project compiles just fine.  I was trying to do the cerbero build from scratch but was running into this error when building the Mac OS X host build:

$ ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc
...
checking for xmlcatalog... /Library/Frameworks/OpenWebRTC.framework/Versions/0.3/bin/xmlcatalog
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog

**Comment by superdump** [comment]
That's something I broke yesterday and didn't manage to fix before I had to stop. First priority when I get to the office. :smile:

**Comment by superdump** [comment]
I was getting this working: http://ericssonresearch.github.io/openwebrtc/docs/gtk-doc/dev/

**Comment by superdump** [comment]
The docbook issue should now be fixed.

**Comment by jrosssavant** [comment]
Thanks, after a pull the build completed successfully and generated the package as expected.
