### ISSUE TITLE
iOS Simple demo app crash before showing video

### ISSUE THREAD

**Issue by ksenks** [EricssonResearch/openwebrtc-examples#59]
The log shows the following:

(<unknown>:1263): GStreamer-CRITICAL **: guint64 _gst_util_uint64_scale(guint64, guint64, guint64, guint64): assertion `denom != 0' failed

(<unknown>:1263): GStreamer-CRITICAL **: guint64 _gst_util_uint64_scale(guint64, guint64, guint64, guint64): assertion `denom != 0' failed
(lldb)

**Comment by stefanalund** [comment]
Which sample app are you referring to?

**Comment by ksenks** [comment]
The sample that called "SimpleDemo": https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/SimpleDemo

**Comment by stefanalund** [comment]
Next question 😊

Did you build OpenWebRTC with Cerbero or the scripts?

**Comment by ksenks** [comment]
Building OpenWebRTC as described here:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

**Comment by EvilTrev** [comment]
I also see plenty of those errors, I built myself using the same guide. I've found it to cause black windows without the remote session showing in them... I see the same error in my build of Bowser as well as the simple demos.

**Comment by jayasuryakumar** [comment]
Appreciate if there is a resolution to the issue by @ksenks

**Comment by stefanalund** [comment]
We have now moved to using the Cerbero instead of the one you used, please see this blog post for details: http://www.openwebrtc.io/blog/2015/3/26/new-official-build-system

As part of this move we will soon start providing pre-build libraries (or .framework's) that you can drop in to your app. These can be accessed though CocoaPods: https://github.com/EricssonResearch/openwebrtc-ios-sdk

(an older version of the framework can be downloaded here:
http://static.verkstad.net/OpenWebRTC.framework_old.zip)

Please let me know if this solves your issue!

Thanks

**Comment by stefanalund** [comment]
This has been confirmed to work, let us know if you still have problems.
