### ISSUE TITLE
NativeCall Sample App wrong camera orientation and video receive black screen flicker

### ISSUE THREAD

**Issue by edmandiesamonte** [EricssonResearch/openwebrtc-examples#75]
Hello,

Upon updating to the latest version of the examples, I notice the following bugs on the NativeCall app.

* The video rendered coming from the opposite end (in my case, Chrome on Mac) flickers with black screen even if both devices are in the same network
* The camera orientation is not correct.

Please see the video here: http://bit.ly/1CJJ9SP

I'm using Sony Xperia Z3 with Android Lollipop 5.1 and Chrome 41.0.2272.118 on Mac OS X Yosemite 10.10.3

**Comment by superdump** [comment]
Your first point is: https://github.com/EricssonResearch/openwebrtc/issues/299
You second point is: https://github.com/EricssonResearch/openwebrtc/issues/150

We are actively working on both those issues right now. Thanks for the report, but please track those two issues instead of this one. I will close this.
